feat: allow user to pass account into Txopt
bnb-chain/greenfield pull request #276
Opened 2023-06-05 04:24 UTC by alexgao001

### Description

add account(accountNum, keyManager) into txOpt, so that allow large batch of txs sent by single client

### Rationale

batch tx sending

### Example

NA

### Changes

Notable changes: 
* NA

2023-06-05 05:18 UTC, Pythonberg1997 approved these changes

2023-06-05 11:06 UTC, guagualvcha approved these changes

2023-06-05 11:06 UTC, guagualvcha approved these changes

2023-06-06 04:13 UTC, guagualvcha commented on sdk/client/tx.go
> +		accountNum = *txOpt.OverrideAccount.Num
`accountNum` seems newly introduced, why don't we only introduce `overide keymanager`, and keep other logic unchanged>

2023-06-06 04:15 UTC, guagualvcha requested changes
Need discussion

2023-06-06 06:16 UTC, Pythonberg1997 commented on sdk/client/tx.go
> +	account, err := c.getAccount(&km)
I prefer this:
```suggestion
        var nonce uint64
	if txOpt != nil && txOpt.Nonce != 0 {
		nonce = txOpt.Nonce
	} else {
	        account, err := c.getAccount(&km)
	        if err != nil {
		        return nil, err
	        }
	        nonce := account.GetSequence()
	}
```

2023-06-06 08:56 UTC, guagualvcha commented on sdk/client/tx.go
> +func (c *GreenfieldClient) GetNonceByKeyManager(km keys.KeyManager) (uint64, error) {
So is this.

2023-06-06 09:07 UTC, guagualvcha approved these changes

2023-06-06 09:17 UTC, merged