fix: policy key is not GC while a expired policy is GC
bnb-chain/greenfield pull request #511
Opened 2023-10-27 09:02 UTC by alexgao001

### Description

When a policy is expired, it should be automatically removed from the store with these two mappings:

1.  policyId -> policy
2. policyKey -> policyId

currently `policyKey -> policyId` is missing so that when a user would fail to re-put policy on the same resource.

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* add each change in a bullet point here
* ...

2023-10-27 09:08 UTC, zjubfd approved these changes

2023-10-27 09:14 UTC, zjubfd requested changes
Need more discussion

2023-10-27 09:42 UTC, Fynnss approved these changes
LGTM

2023-10-27 15:31 UTC, Pythonberg1997 approved these changes

2023-10-30 09:07 UTC, zjubfd approved these changes

2023-10-30 09:07 UTC, merged