fix: seal object validate if secondary SP in_service
bnb-chain/greenfield pull request #561
Opened 2024-01-15 02:58 UTC by alexgao001

### Description

seal object validate if secondary SP in_service, in case that SP is exiting but still need to severs as a secondary SP. 

### Rationale

SP not in_service should not serve users requests. 

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* add each change in a bullet point here
* ...

### Potential Impacts
* add potential impacts for other components here
* ...

2024-01-15 03:14 UTC, zjubfd approved these changes

2024-01-15 03:15 UTC, zjubfd approved these changes

2024-01-15 03:16 UTC, KeefeL approved these changes

2024-01-15 03:17 UTC, zjubfd requested changes
need more consideration

2024-01-19 06:56 UTC, zjubfd commented
hold on first

2024-05-31 07:30 UTC, closed without merging